#cp ./legacy.mk ../openwrt/target/linux/ar71xx/image/legacy.mk
#cp ./common-tp-link.mk ../openwrt/target/linux/ar71xx/image/common-tp-link.mk
cp ./shadow ../openwrt/package/base-files/files/etc/shadow
cp ./hosts ../openwrt/package/base-files/files/etc/hosts
cp ./config_generate ../openwrt/package/base-files/files/bin/config_generate
cp ./mac80211.sh ../openwrt/package/kernel/mac80211/files/lib/wifi/mac80211.sh
cp ./luci ../openwrt/feeds/luci/modules/luci-base/root/etc/config/luci
cp ./dhcp.conf ../openwrt/package/network/services/dnsmasq/files/dhcp.conf
#cp ./dnsmasq.conf ../openwrt/package/network/services/dnsmasq/files/dnsmasq.conf
