#cp ./legacy.mk $GITHUB_WORKSPACE/openwrt/target/linux/ar71xx/image/legacy.mk
#cp ./common-tp-link.mk $GITHUB_WORKSPACE/openwrt/target/linux/ar71xx/image/common-tp-link.mk
cp ./shadow $GITHUB_WORKSPACE/openwrt/package/base-files/files/etc/shadow
cp ./hosts $GITHUB_WORKSPACE/openwrt/package/base-files/files/etc/hosts
cp ./config_generate $GITHUB_WORKSPACE/openwrt/package/base-files/files/bin/config_generate
cp ./mac80211.sh $GITHUB_WORKSPACE/openwrt/package/kernel/mac80211/files/lib/wifi/mac80211.sh
cp ./luci $GITHUB_WORKSPACE/openwrt/feeds/luci/modules/luci-base/root/etc/config/luci
cp ./dhcp.conf $GITHUB_WORKSPACE/openwrt/package/network/services/dnsmasq/files/dhcp.conf
#cp ./dnsmasq.conf $GITHUB_WORKSPACE/sunxi/package/network/services/dnsmasq/files/dnsmasq.conf
